steps:

#install
- name: 'gcr.io/cloud-builders/npm'
args: ['install']

#test
- name: 'gcr.io/cloud-builders/npm'
args: ['run', 'test:unit']

#build 
- name: 'gcr.io/cloud-builders/npm'
args: ['run', 'build']

#deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
args: ['deploy']

